// flow-typed signature: 35c30f6f7da44b0c927f9df0115b8cfb
// flow-typed version: <<STUB>>/node-cron_v^1.2.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-cron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-cron' {
	declare class CronJob {
		constructor(
			cronTime: number | string,
			onTick: any,
			onComplete: any,
			startNow: boolean,
			timeZone: string,
			context: any,
			runOnInit: any
		): any,
		start(): void
	}
	declare export default typeof CronJob;
}
